### ISSUE TITLE
`--sos` stop on success flag is not working 

### ISSUE THREAD

**Issue by bugbaba** [gwen001/testxss#1]
Hi Gwen,

While i am trying this project, i happen to fall on a bug.

So there is a flag `--sos` that needs to stop the process when the success is found 

But actually it is still sending the requests after the success is found.

To verify i created a simple vulnerable page in php on my localhost

And I am using verbose = 0 (everything) flag while running the testxss

 

```
andro@lab:~/testxss (master%=) % php testxss.php --prefix --suffix --sos --inject=GPCHU --threads=10 --verbose=0 --phantom=/usr/local/bin/phantomjs --urls=urls.txt  --payload=payload.txt

Loading urls from file 'urls.txt'...
1 request(s) has been loaded.
Loading payloads from file 'payload.txt'...
4 payload(s) has been loaded.
Parameters GPCHU will be tested.

Running 10 threads...

Request 1/1 -> http://localhost/lol.php?bc=aa
    Payload 1/4 -> injection: "><script>alert(1);</script>
        URL '/lol.php' seems to be SAFE
        GET parameter 'bc' seems to be VULNERABLE with value: aa"><script>alert(1);</script>
Request 1/1 -> http://localhost/lol.php?bc=aa
    Payload 2/4 -> injection: payload2
        URL '/lol.php' seems to be SAFE
        GET parameter 'bc' seems to be SAFE
Request 1/1 -> http://localhost/lol.php?bc=aa
    Payload 3/4 -> injection: payload3
        URL '/lol.php' seems to be SAFE
        GET parameter 'bc' seems to be SAFE
Request 1/1 -> http://localhost/lol.php?bc=aa
    Payload 4/4 -> injection: "></script>alert(1);</script>
        URL '/lol.php' seems to be SAFE
        GET parameter 'bc' seems to be SAFE

The end.
```

As you can see even when it got success from first payload it is still sending request with other payloads.

I have again confirm this by checking the access log of the server 

```
127.0.0.1 - - [12/May/2018:16:48:22 +0200] "GET /lol.php/%22%3E%3Cscript%3Ealert(1);%3C/script%3E/?bc=aa HTTP/1.1" 200 205 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
127.0.0.1 - - [12/May/2018:16:48:22 +0200] "GET /lol.php/payload2/?bc=aa HTTP/1.1" 200 205 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
127.0.0.1 - - [12/May/2018:16:48:22 +0200] "GET /lol.php/payload3/?bc=aa HTTP/1.1" 200 205 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
127.0.0.1 - - [12/May/2018:16:48:22 +0200] "GET /lol.php/%22%3E%3C/script%3Ealert(1);%3C/script%3E/?bc=aa HTTP/1.1" 200 205 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
127.0.0.1 - - [12/May/2018:16:48:22 +0200] "GET /lol.php?bc=aa%22%3E%3Cscript%3Ealert(1);%3C/script%3E HTTP/1.1" 200 234 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
127.0.0.1 - - [12/May/2018:16:48:22 +0200] "GET /lol.php?bc=aapayload2 HTTP/1.1" 200 214 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
127.0.0.1 - - [12/May/2018:16:48:22 +0200] "GET /lol.php?bc=aapayload3 HTTP/1.1" 200 214 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
127.0.0.1 - - [12/May/2018:16:48:22 +0200] "GET /lol.php?bc=aa%22%3E%3C/script%3Ealert(1);%3C/script%3E HTTP/1.1" 200 235 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"

```

Hope this helps :) 

Regards,

**Comment by gwen001** [comment]
See how many payloads do you have in your payload file? Only 4 have been tested in this case.
It works, the program stopped after the first valid result but since it's multi threaded, some other requests have been sent at the same time.

If you set `--threads 1`you will see that it will stop after the first vulnerable finding.

**Comment by bugbaba** [comment]
Yes i have kept `4` payloads in the file 


And even with `--threads 1` 
it is still able to make one more  request after  success 

![sss](https://user-images.githubusercontent.com/29960776/39958682-d2f4145c-5623-11e8-8316-38d10d7d5ddf.png)


Is this the case 
because i am testing on local machine 
so time to stop threads  is slower then the speed to get response ? just a thought

**Comment by gwen001** [comment]
It's because of the `sleep()` function line 620, one more request is performed. If you comment it, it doesn't happen anymore and the program is faster, but it can also be more cpu consuming. You can try to reduce it if it really a problem for you.

**Comment by bugbaba** [comment]
Thanks :+1:
